language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install --upgrade pip setuptools
  - pip install tox tox-travis coveralls codeclimate-test-reporter
script:
  - tox
after_success:
  - coveralls
addons:
  apt:
    packages:
    - libgsl0-dev
deploy:
  provider: pypi
  user: rob.beagrie
  password:
    secure: L4myeBx61HAtwAufRuTyXFmA4RAp3vAwLAC8Iv12/yhtImci8+veMsNOJrfgIgrI6zRf+Ao2CJT35SMTYMWGBwDCSrbePZYsUj43wudEpXKMCKO+uVWRlEaPTEBXvOCCjq6QlmNdPCtlbqO511DrD7oWdzACIwxaEN4Jy4yACBpIpxH9hIE8/UmkRaq2MLhAIhclLeu1eALtb6gFjm1xJzntfih338a/vCauul5R10iE77/1jhLsRv1pu4M2wfar543rjfj2gcx0qVZiNJueoj1QLsFR/x3wlsdacsPjmoWDes0z0b0BeXBS7Vn5/ZQ3PoeU80zsnrtr8kE/TtrERZhmByeqAcXnjkWU+Rw5sUcfCE9bpIgL60ndgd/oviXjYnWNqLMay/nrIU/rksuHW9Mg6EIcNRKuAAXFpc0+BxNIx6nXpuowUcpNHaekuNhN91PUGcQi6XbDkeHE3SbYDdXflLE2xa6bOHh9iG1auwX9CWGX75JyH1AGJEE9Mi+Y06Oeptqm8lotk597CuowEyZQZAmOeJccHt4Kqg1Zaswz1yaqPQziJRzmC1p9EC+wUXsAfcbuoFGWohuFCZqb0EXNLns/MpPWIhvtKhzDkv1kZ91089HpTVRxaR3q+5zXg2y+2rdRXnTOt2aJuf0zRzX1F5FcVpJDMTem6fcbj3g=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pombo-lab/gamtools
